( cd opt/metasploit-framework/embedded/bin ; rm -rf captoinfo )
( cd opt/metasploit-framework/embedded/bin ; ln -sf tic captoinfo )
( cd opt/metasploit-framework/embedded/bin ; rm -rf infotocap )
( cd opt/metasploit-framework/embedded/bin ; ln -sf tic infotocap )
( cd opt/metasploit-framework/embedded/bin ; rm -rf lzcat )
( cd opt/metasploit-framework/embedded/bin ; ln -sf xz lzcat )
( cd opt/metasploit-framework/embedded/bin ; rm -rf lzma )
( cd opt/metasploit-framework/embedded/bin ; ln -sf xz lzma )
( cd opt/metasploit-framework/embedded/bin ; rm -rf postmaster )
( cd opt/metasploit-framework/embedded/bin ; ln -sf postgres postmaster )
( cd opt/metasploit-framework/embedded/bin ; rm -rf reset )
( cd opt/metasploit-framework/embedded/bin ; ln -sf tset reset )
( cd opt/metasploit-framework/embedded/bin ; rm -rf unlzma )
( cd opt/metasploit-framework/embedded/bin ; ln -sf xz unlzma )
( cd opt/metasploit-framework/embedded/bin ; rm -rf unxz )
( cd opt/metasploit-framework/embedded/bin ; ln -sf xz unxz )
( cd opt/metasploit-framework/embedded/bin ; rm -rf xzcat )
( cd opt/metasploit-framework/embedded/bin ; ln -sf xz xzcat )
( cd opt/metasploit-framework/embedded/include ; rm -rf ncurses.h )
( cd opt/metasploit-framework/embedded/include ; ln -sf curses.h ncurses.h )
( cd opt/metasploit-framework/embedded/lib ; rm -rf libcrypto.so )
( cd opt/metasploit-framework/embedded/lib ; ln -sf libcrypto.so.1.1 libcrypto.so )
( cd opt/metasploit-framework/embedded/lib ; rm -rf libcurses.a )
( cd opt/metasploit-framework/embedded/lib ; ln -sf libncurses.a libcurses.a )
( cd opt/metasploit-framework/embedded/lib ; rm -rf libcurses.so )
( cd opt/metasploit-framework/embedded/lib ; ln -sf libncurses.so.6.2 libcurses.so )
( cd opt/metasploit-framework/embedded/lib ; rm -rf libecpg.so )
( cd opt/metasploit-framework/embedded/lib ; ln -sf libecpg.so.6.13 libecpg.so )
( cd opt/metasploit-framework/embedded/lib ; rm -rf libecpg.so.6 )
( cd opt/metasploit-framework/embedded/lib ; ln -sf libecpg.so.6.13 libecpg.so.6 )
( cd opt/metasploit-framework/embedded/lib ; rm -rf libecpg_compat.so )
( cd opt/metasploit-framework/embedded/lib ; ln -sf libecpg_compat.so.3.13 libecpg_compat.so )
( cd opt/metasploit-framework/embedded/lib ; rm -rf libecpg_compat.so.3 )
( cd opt/metasploit-framework/embedded/lib ; ln -sf libecpg_compat.so.3.13 libecpg_compat.so.3 )
( cd opt/metasploit-framework/embedded/lib ; rm -rf libedit.so )
( cd opt/metasploit-framework/embedded/lib ; ln -sf libedit.so.0.0.55 libedit.so )
( cd opt/metasploit-framework/embedded/lib ; rm -rf libedit.so.0 )
( cd opt/metasploit-framework/embedded/lib ; ln -sf libedit.so.0.0.55 libedit.so.0 )
( cd opt/metasploit-framework/embedded/lib ; rm -rf libexslt.so )
( cd opt/metasploit-framework/embedded/lib ; ln -sf libexslt.so.0.8.20 libexslt.so )
( cd opt/metasploit-framework/embedded/lib ; rm -rf libexslt.so.0 )
( cd opt/metasploit-framework/embedded/lib ; ln -sf libexslt.so.0.8.20 libexslt.so.0 )
( cd opt/metasploit-framework/embedded/lib ; rm -rf libffi.so )
( cd opt/metasploit-framework/embedded/lib ; ln -sf libffi.so.8.1.0 libffi.so )
( cd opt/metasploit-framework/embedded/lib ; rm -rf libffi.so.8 )
( cd opt/metasploit-framework/embedded/lib ; ln -sf libffi.so.8.1.0 libffi.so.8 )
( cd opt/metasploit-framework/embedded/lib ; rm -rf libform.so )
( cd opt/metasploit-framework/embedded/lib ; ln -sf libform.so.6 libform.so )
( cd opt/metasploit-framework/embedded/lib ; rm -rf libform.so.6 )
( cd opt/metasploit-framework/embedded/lib ; ln -sf libform.so.6.2 libform.so.6 )
( cd opt/metasploit-framework/embedded/lib ; rm -rf libformw.so )
( cd opt/metasploit-framework/embedded/lib ; ln -sf libformw.so.6 libformw.so )
( cd opt/metasploit-framework/embedded/lib ; rm -rf libformw.so.6 )
( cd opt/metasploit-framework/embedded/lib ; ln -sf libformw.so.6.2 libformw.so.6 )
( cd opt/metasploit-framework/embedded/lib ; rm -rf libjemalloc.so )
( cd opt/metasploit-framework/embedded/lib ; ln -sf libjemalloc.so.2 libjemalloc.so )
( cd opt/metasploit-framework/embedded/lib ; rm -rf liblzma.so )
( cd opt/metasploit-framework/embedded/lib ; ln -sf liblzma.so.5.2.3 liblzma.so )
( cd opt/metasploit-framework/embedded/lib ; rm -rf liblzma.so.5 )
( cd opt/metasploit-framework/embedded/lib ; ln -sf liblzma.so.5.2.3 liblzma.so.5 )
( cd opt/metasploit-framework/embedded/lib ; rm -rf libmenu.so )
( cd opt/metasploit-framework/embedded/lib ; ln -sf libmenu.so.6 libmenu.so )
( cd opt/metasploit-framework/embedded/lib ; rm -rf libmenu.so.6 )
( cd opt/metasploit-framework/embedded/lib ; ln -sf libmenu.so.6.2 libmenu.so.6 )
( cd opt/metasploit-framework/embedded/lib ; rm -rf libmenuw.so )
( cd opt/metasploit-framework/embedded/lib ; ln -sf libmenuw.so.6 libmenuw.so )
( cd opt/metasploit-framework/embedded/lib ; rm -rf libmenuw.so.6 )
( cd opt/metasploit-framework/embedded/lib ; ln -sf libmenuw.so.6.2 libmenuw.so.6 )
( cd opt/metasploit-framework/embedded/lib ; rm -rf libncurses.so )
( cd opt/metasploit-framework/embedded/lib ; ln -sf libncurses.so.6 libncurses.so )
( cd opt/metasploit-framework/embedded/lib ; rm -rf libncurses.so.6 )
( cd opt/metasploit-framework/embedded/lib ; ln -sf libncurses.so.6.2 libncurses.so.6 )
( cd opt/metasploit-framework/embedded/lib ; rm -rf libncursesw.so )
( cd opt/metasploit-framework/embedded/lib ; ln -sf libncursesw.so.6 libncursesw.so )
( cd opt/metasploit-framework/embedded/lib ; rm -rf libncursesw.so.6 )
( cd opt/metasploit-framework/embedded/lib ; ln -sf libncursesw.so.6.2 libncursesw.so.6 )
( cd opt/metasploit-framework/embedded/lib ; rm -rf libpanel.so )
( cd opt/metasploit-framework/embedded/lib ; ln -sf libpanel.so.6 libpanel.so )
( cd opt/metasploit-framework/embedded/lib ; rm -rf libpanel.so.6 )
( cd opt/metasploit-framework/embedded/lib ; ln -sf libpanel.so.6.2 libpanel.so.6 )
( cd opt/metasploit-framework/embedded/lib ; rm -rf libpanelw.so )
( cd opt/metasploit-framework/embedded/lib ; ln -sf libpanelw.so.6 libpanelw.so )
( cd opt/metasploit-framework/embedded/lib ; rm -rf libpanelw.so.6 )
( cd opt/metasploit-framework/embedded/lib ; ln -sf libpanelw.so.6.2 libpanelw.so.6 )
( cd opt/metasploit-framework/embedded/lib ; rm -rf libpcap.so )
( cd opt/metasploit-framework/embedded/lib ; ln -sf libpcap.so.1 libpcap.so )
( cd opt/metasploit-framework/embedded/lib ; rm -rf libpcap.so.1 )
( cd opt/metasploit-framework/embedded/lib ; ln -sf libpcap.so.1.6.2 libpcap.so.1 )
( cd opt/metasploit-framework/embedded/lib ; rm -rf libpgtypes.so )
( cd opt/metasploit-framework/embedded/lib ; ln -sf libpgtypes.so.3.13 libpgtypes.so )
( cd opt/metasploit-framework/embedded/lib ; rm -rf libpgtypes.so.3 )
( cd opt/metasploit-framework/embedded/lib ; ln -sf libpgtypes.so.3.13 libpgtypes.so.3 )
( cd opt/metasploit-framework/embedded/lib ; rm -rf libpq.so )
( cd opt/metasploit-framework/embedded/lib ; ln -sf libpq.so.5.13 libpq.so )
( cd opt/metasploit-framework/embedded/lib ; rm -rf libpq.so.5 )
( cd opt/metasploit-framework/embedded/lib ; ln -sf libpq.so.5.13 libpq.so.5 )
( cd opt/metasploit-framework/embedded/lib ; rm -rf libruby.so )
( cd opt/metasploit-framework/embedded/lib ; ln -sf libruby.so.3.4.4 libruby.so )
( cd opt/metasploit-framework/embedded/lib ; rm -rf libruby.so.3.4 )
( cd opt/metasploit-framework/embedded/lib ; ln -sf libruby.so.3.4.4 libruby.so.3.4 )
( cd opt/metasploit-framework/embedded/lib ; rm -rf libssl.so )
( cd opt/metasploit-framework/embedded/lib ; ln -sf libssl.so.1.1 libssl.so )
( cd opt/metasploit-framework/embedded/lib ; rm -rf libtinfo.so )
( cd opt/metasploit-framework/embedded/lib ; ln -sf libtinfo.so.6 libtinfo.so )
( cd opt/metasploit-framework/embedded/lib ; rm -rf libtinfo.so.6 )
( cd opt/metasploit-framework/embedded/lib ; ln -sf libtinfo.so.6.2 libtinfo.so.6 )
( cd opt/metasploit-framework/embedded/lib ; rm -rf libtinfow.so )
( cd opt/metasploit-framework/embedded/lib ; ln -sf libtinfow.so.6 libtinfow.so )
( cd opt/metasploit-framework/embedded/lib ; rm -rf libtinfow.so.6 )
( cd opt/metasploit-framework/embedded/lib ; ln -sf libtinfow.so.6.2 libtinfow.so.6 )
( cd opt/metasploit-framework/embedded/lib ; rm -rf libuuid.so )
( cd opt/metasploit-framework/embedded/lib ; ln -sf libuuid.so.1.3.0 libuuid.so )
( cd opt/metasploit-framework/embedded/lib ; rm -rf libuuid.so.1 )
( cd opt/metasploit-framework/embedded/lib ; ln -sf libuuid.so.1.3.0 libuuid.so.1 )
( cd opt/metasploit-framework/embedded/lib ; rm -rf libxml2.so )
( cd opt/metasploit-framework/embedded/lib ; ln -sf libxml2.so.2.9.10 libxml2.so )
( cd opt/metasploit-framework/embedded/lib ; rm -rf libxml2.so.2 )
( cd opt/metasploit-framework/embedded/lib ; ln -sf libxml2.so.2.9.10 libxml2.so.2 )
( cd opt/metasploit-framework/embedded/lib ; rm -rf libxslt.so )
( cd opt/metasploit-framework/embedded/lib ; ln -sf libxslt.so.1.1.34 libxslt.so )
( cd opt/metasploit-framework/embedded/lib ; rm -rf libxslt.so.1 )
( cd opt/metasploit-framework/embedded/lib ; ln -sf libxslt.so.1.1.34 libxslt.so.1 )
( cd opt/metasploit-framework/embedded/lib ; rm -rf libyaml-0.so.2 )
( cd opt/metasploit-framework/embedded/lib ; ln -sf libyaml-0.so.2.0.5 libyaml-0.so.2 )
( cd opt/metasploit-framework/embedded/lib ; rm -rf libyaml.so )
( cd opt/metasploit-framework/embedded/lib ; ln -sf libyaml-0.so.2.0.5 libyaml.so )
( cd opt/metasploit-framework/embedded/lib ; rm -rf libz.so )
( cd opt/metasploit-framework/embedded/lib ; ln -sf libz.so.1.2.11 libz.so )
( cd opt/metasploit-framework/embedded/lib ; rm -rf libz.so.1 )
( cd opt/metasploit-framework/embedded/lib ; ln -sf libz.so.1.2.11 libz.so.1 )
( cd opt/metasploit-framework/embedded/lib/ruby/gems/3.4.0/gems/sqlite3-1.7.3/ext/sqlite3/tmp/x86_64-linux-gnu/ports/sqlite3/3.45.2/sqlite-autoconf-3450200/.libs ; rm -rf libsqlite3.la )
( cd opt/metasploit-framework/embedded/lib/ruby/gems/3.4.0/gems/sqlite3-1.7.3/ext/sqlite3/tmp/x86_64-linux-gnu/ports/sqlite3/3.45.2/sqlite-autoconf-3450200/.libs ; ln -sf ../libsqlite3.la libsqlite3.la )
( cd opt/metasploit-framework/embedded/lib ; rm -rf terminfo )
( cd opt/metasploit-framework/embedded/lib ; ln -sf ../share/terminfo terminfo )
( cd opt/metasploit-framework/embedded/share/man/man1 ; rm -rf lzcat.1 )
( cd opt/metasploit-framework/embedded/share/man/man1 ; ln -sf xz.1 lzcat.1 )
( cd opt/metasploit-framework/embedded/share/man/man1 ; rm -rf lzma.1 )
( cd opt/metasploit-framework/embedded/share/man/man1 ; ln -sf xz.1 lzma.1 )
( cd opt/metasploit-framework/embedded/share/man/man1 ; rm -rf lzmadec.1 )
( cd opt/metasploit-framework/embedded/share/man/man1 ; ln -sf xzdec.1 lzmadec.1 )
( cd opt/metasploit-framework/embedded/share/man/man1 ; rm -rf unlzma.1 )
( cd opt/metasploit-framework/embedded/share/man/man1 ; ln -sf xz.1 unlzma.1 )
( cd opt/metasploit-framework/embedded/share/man/man1 ; rm -rf unxz.1 )
( cd opt/metasploit-framework/embedded/share/man/man1 ; ln -sf xz.1 unxz.1 )
( cd opt/metasploit-framework/embedded/share/man/man1 ; rm -rf xzcat.1 )
( cd opt/metasploit-framework/embedded/share/man/man1 ; ln -sf xz.1 xzcat.1 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; rm -rf el_deletestr.3 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; ln -sf editline.3 el_deletestr.3 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; rm -rf el_end.3 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; ln -sf editline.3 el_end.3 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; rm -rf el_get.3 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; ln -sf editline.3 el_get.3 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; rm -rf el_getc.3 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; ln -sf editline.3 el_getc.3 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; rm -rf el_gets.3 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; ln -sf editline.3 el_gets.3 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; rm -rf el_init.3 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; ln -sf editline.3 el_init.3 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; rm -rf el_init_fd.3 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; ln -sf editline.3 el_init_fd.3 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; rm -rf el_insertstr.3 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; ln -sf editline.3 el_insertstr.3 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; rm -rf el_line.3 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; ln -sf editline.3 el_line.3 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; rm -rf el_parse.3 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; ln -sf editline.3 el_parse.3 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; rm -rf el_push.3 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; ln -sf editline.3 el_push.3 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; rm -rf el_reset.3 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; ln -sf editline.3 el_reset.3 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; rm -rf el_resize.3 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; ln -sf editline.3 el_resize.3 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; rm -rf el_set.3 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; ln -sf editline.3 el_set.3 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; rm -rf el_source.3 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; ln -sf editline.3 el_source.3 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; rm -rf el_wdeletestr.3 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; ln -sf editline.3 el_wdeletestr.3 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; rm -rf el_wget.3 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; ln -sf editline.3 el_wget.3 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; rm -rf el_wgetc.3 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; ln -sf editline.3 el_wgetc.3 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; rm -rf el_wgets.3 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; ln -sf editline.3 el_wgets.3 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; rm -rf el_winsertstr.3 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; ln -sf editline.3 el_winsertstr.3 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; rm -rf el_wline.3 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; ln -sf editline.3 el_wline.3 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; rm -rf el_wparse.3 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; ln -sf editline.3 el_wparse.3 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; rm -rf el_wpush.3 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; ln -sf editline.3 el_wpush.3 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; rm -rf el_wset.3 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; ln -sf editline.3 el_wset.3 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; rm -rf history.3 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; ln -sf editline.3 history.3 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; rm -rf history_end.3 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; ln -sf editline.3 history_end.3 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; rm -rf history_init.3 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; ln -sf editline.3 history_init.3 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; rm -rf history_w.3 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; ln -sf editline.3 history_w.3 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; rm -rf history_wend.3 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; ln -sf editline.3 history_wend.3 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; rm -rf history_winit.3 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; ln -sf editline.3 history_winit.3 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; rm -rf pcap_datalink_val_to_description.3pcap )
( cd opt/metasploit-framework/embedded/share/man/man3 ; ln -sf pcap_datalink_val_to_name.3pcap pcap_datalink_val_to_description.3pcap )
( cd opt/metasploit-framework/embedded/share/man/man3 ; rm -rf pcap_dispatch.3pcap )
( cd opt/metasploit-framework/embedded/share/man/man3 ; ln -sf pcap_loop.3pcap pcap_dispatch.3pcap )
( cd opt/metasploit-framework/embedded/share/man/man3 ; rm -rf pcap_dump_fopen.3pcap )
( cd opt/metasploit-framework/embedded/share/man/man3 ; ln -sf pcap_dump_open.3pcap pcap_dump_fopen.3pcap )
( cd opt/metasploit-framework/embedded/share/man/man3 ; rm -rf pcap_fopen_offline.3pcap )
( cd opt/metasploit-framework/embedded/share/man/man3 ; ln -sf pcap_open_offline.3pcap pcap_fopen_offline.3pcap )
( cd opt/metasploit-framework/embedded/share/man/man3 ; rm -rf pcap_fopen_offline_with_tstamp_precision.3pcap )
( cd opt/metasploit-framework/embedded/share/man/man3 ; ln -sf pcap_open_offline.3pcap pcap_fopen_offline_with_tstamp_precision.3pcap )
( cd opt/metasploit-framework/embedded/share/man/man3 ; rm -rf pcap_free_datalinks.3pcap )
( cd opt/metasploit-framework/embedded/share/man/man3 ; ln -sf pcap_list_datalinks.3pcap pcap_free_datalinks.3pcap )
( cd opt/metasploit-framework/embedded/share/man/man3 ; rm -rf pcap_free_tstamp_types.3pcap )
( cd opt/metasploit-framework/embedded/share/man/man3 ; ln -sf pcap_list_tstamp_types.3pcap pcap_free_tstamp_types.3pcap )
( cd opt/metasploit-framework/embedded/share/man/man3 ; rm -rf pcap_freealldevs.3pcap )
( cd opt/metasploit-framework/embedded/share/man/man3 ; ln -sf pcap_findalldevs.3pcap pcap_freealldevs.3pcap )
( cd opt/metasploit-framework/embedded/share/man/man3 ; rm -rf pcap_getnonblock.3pcap )
( cd opt/metasploit-framework/embedded/share/man/man3 ; ln -sf pcap_setnonblock.3pcap pcap_getnonblock.3pcap )
( cd opt/metasploit-framework/embedded/share/man/man3 ; rm -rf pcap_minor_version.3pcap )
( cd opt/metasploit-framework/embedded/share/man/man3 ; ln -sf pcap_major_version.3pcap pcap_minor_version.3pcap )
( cd opt/metasploit-framework/embedded/share/man/man3 ; rm -rf pcap_next.3pcap )
( cd opt/metasploit-framework/embedded/share/man/man3 ; ln -sf pcap_next_ex.3pcap pcap_next.3pcap )
( cd opt/metasploit-framework/embedded/share/man/man3 ; rm -rf pcap_open_dead_with_tstamp_precision.3pcap )
( cd opt/metasploit-framework/embedded/share/man/man3 ; ln -sf pcap_open_dead.3pcap pcap_open_dead_with_tstamp_precision.3pcap )
( cd opt/metasploit-framework/embedded/share/man/man3 ; rm -rf pcap_open_offline_with_tstamp_precision.3pcap )
( cd opt/metasploit-framework/embedded/share/man/man3 ; ln -sf pcap_open_offline.3pcap pcap_open_offline_with_tstamp_precision.3pcap )
( cd opt/metasploit-framework/embedded/share/man/man3 ; rm -rf pcap_perror.3pcap )
( cd opt/metasploit-framework/embedded/share/man/man3 ; ln -sf pcap_geterr.3pcap pcap_perror.3pcap )
( cd opt/metasploit-framework/embedded/share/man/man3 ; rm -rf pcap_sendpacket.3pcap )
( cd opt/metasploit-framework/embedded/share/man/man3 ; ln -sf pcap_inject.3pcap pcap_sendpacket.3pcap )
( cd opt/metasploit-framework/embedded/share/man/man3 ; rm -rf pcap_tstamp_type_val_to_description.3pcap )
( cd opt/metasploit-framework/embedded/share/man/man3 ; ln -sf pcap_tstamp_type_val_to_name.3pcap pcap_tstamp_type_val_to_description.3pcap )
( cd opt/metasploit-framework/embedded/share/man/man3 ; rm -rf tok_end.3 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; ln -sf editline.3 tok_end.3 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; rm -rf tok_init.3 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; ln -sf editline.3 tok_init.3 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; rm -rf tok_line.3 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; ln -sf editline.3 tok_line.3 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; rm -rf tok_reset.3 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; ln -sf editline.3 tok_reset.3 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; rm -rf tok_str.3 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; ln -sf editline.3 tok_str.3 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; rm -rf tok_wend.3 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; ln -sf editline.3 tok_wend.3 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; rm -rf tok_winit.3 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; ln -sf editline.3 tok_winit.3 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; rm -rf tok_wline.3 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; ln -sf editline.3 tok_wline.3 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; rm -rf tok_wreset.3 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; ln -sf editline.3 tok_wreset.3 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; rm -rf tok_wstr.3 )
( cd opt/metasploit-framework/embedded/share/man/man3 ; ln -sf editline.3 tok_wstr.3 )
( cd opt/metasploit-framework/embedded/ssl ; rm -rf cert.pem )
( cd opt/metasploit-framework/embedded/ssl ; ln -sf certs/cacert.pem cert.pem )
( cd opt/metasploit-framework/embedded/ssl/misc ; rm -rf tsget )
( cd opt/metasploit-framework/embedded/ssl/misc ; ln -sf tsget.pl tsget )
( cd usr/bin ; rm -rf msfbinscan )
( cd usr/bin ; ln -sf ../../opt/metasploit-framework/bin/msfbinscan msfbinscan )
( cd usr/bin ; rm -rf msfconsole )
( cd usr/bin ; ln -sf ../../opt/metasploit-framework/bin/msfconsole msfconsole )
( cd usr/bin ; rm -rf msfd )
( cd usr/bin ; ln -sf ../../opt/metasploit-framework/bin/msfd msfd )
( cd usr/bin ; rm -rf msfdb )
( cd usr/bin ; ln -sf ../../opt/metasploit-framework/bin/msfdb msfdb )
( cd usr/bin ; rm -rf msfelfscan )
( cd usr/bin ; ln -sf ../../opt/metasploit-framework/bin/msfelfscan msfelfscan )
( cd usr/bin ; rm -rf msfmachscan )
( cd usr/bin ; ln -sf ../../opt/metasploit-framework/bin/msfmachscan msfmachscan )
( cd usr/bin ; rm -rf msfpescan )
( cd usr/bin ; ln -sf ../../opt/metasploit-framework/bin/msfpescan msfpescan )
( cd usr/bin ; rm -rf msfremove )
( cd usr/bin ; ln -sf ../../opt/metasploit-framework/bin/msfremove msfremove )
( cd usr/bin ; rm -rf msfrop )
( cd usr/bin ; ln -sf ../../opt/metasploit-framework/bin/msfrop msfrop )
( cd usr/bin ; rm -rf msfrpc )
( cd usr/bin ; ln -sf ../../opt/metasploit-framework/bin/msfrpc msfrpc )
( cd usr/bin ; rm -rf msfrpcd )
( cd usr/bin ; ln -sf ../../opt/metasploit-framework/bin/msfrpcd msfrpcd )
( cd usr/bin ; rm -rf msfupdate )
( cd usr/bin ; ln -sf ../../opt/metasploit-framework/bin/msfupdate msfupdate )
( cd usr/bin ; rm -rf msfvenom )
( cd usr/bin ; ln -sf ../../opt/metasploit-framework/bin/msfvenom msfvenom )
